### ISSUE TITLE
Missing link to github

### ISSUE THREAD

**Issue by muescha** [phero-hq/website#1]
i miss a link to the phero github repo on website

it is only hidden at github star widget

link in footer goes to docusaurus instead of phero

the navbar github link is not visible because on the hamburger menu you need to click on the left arrow to see the 4 navbar items (normaly you never click this arrow - i searched for it because i seen it in the config)

**Comment by JasperH8g** [comment]
Yeah, that header on mobile is not very useful at the moment 😞 Will fix that asap, thanks!

**Comment by muescha** [comment]
in desktop also
