### ISSUE TITLE
tRPC Comparison - Incorrect Phero Limitation?

### ISSUE THREAD

**Issue by helmturner** [phero-hq/website#7]
Reading through the comparison at https://phero.dev/docs/comparisons/tRPC, the last paragraph under "Defining Your Functions" reads as follows:

> The catch is though: This works for everything that can be described in TypeScript, but nothing more than that. For example: If you've got an email property and you want to validate that it's actually an email, you'd have to do that yourself. The irony is that you totally can use Zod (or any validation-lib) in Phero to do this, but you'll only use it for these specific situations. In our experience, these cases are pretty rare compared to the values that can be defined in plain TypeScript. It's a tradeoff, but worth it in our opinion.

Is this accurate? Can we not use a template-type to validate email?
```
type Email = `${string}@${string}.${string}`
```

**Comment by JasperH8g** [comment]
With the current version, you can't. We are working on quite an improvement iteration, which will most likely include templated strings as well though!

**Comment by helmturner** [comment]
I guess I assumed Phero implements e2e type-safety at the static type level - i.e."you don't need to validate at runtime if everything checks at compile-time on both ends of the system."

After reading your reply I skimmed the code... Y'all are actually parsing the TS! Is Phero performing runtime validation?

**Comment by JasperH8g** [comment]
@helmturner yes, absolutely! We definitely need to explain that better though 😅
